### ISSUE TITLE
Generating the structures too soon?

### ISSUE THREAD

**Issue by wildbill22** [TheXFactor117/Ascension#23]
We use this to register:
GameRegistry.registerWorldGenerator(this.eventWorldGen, 0);
The number is the weight, the lower the number, the sooner this runs relative to other things that generate stuff. In another mod I work on, this is set to 1000.

**Comment by TheXFactor117** [comment]
That's just the number I set for the ores. You can switch it to 1000 and see if it changes other things. I think if we leave it at zero, we may be 'overriding' other mods structures.

If we do decide to change it, I don't think we will be able to fully implement it till Beta 2 simply because people would need to create new worlds, or explore new chunks to get the new world gen. I don't know how big the difference will be with that set higher.

**Comment by wildbill22** [comment]
The problem I keep seeing is that while the "isDecorating" is running (I think this is where grass, trees, etc. is added to the surface), a building attempts to generate and then Minecraft crashes. So the buildings could be created later, and avoid this problem. It is a very difficult problem to solve otherwise.

**Comment by TheXFactor117** [comment]
I did a couple tests with other mods installed as well. Basically, without Ascension installed, other mods structures generate fairly often. With, however, our structures spawn all over the place, and other mod structures chance decreased.

I think this would be an issue with the probability here, and I'll look into it a bit more, but we most likely will need to bump this number up.

**Comment by TheXFactor117** [comment]
Number has been bumped up.
